### ISSUE TITLE
Lack of memes

### ISSUE THREAD

**Issue by installgen2** [wiiam/taylorswift#1]
please add more memes

**Comment by wiiam** [comment]
no

**Comment by installgen2** [comment]
yes

**Comment by wiiam** [comment]
no

**Comment by wiiam** [comment]
wew

**Comment by installgen2** [comment]
I never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that never said that v

**Comment by installgen2** [comment]
memes

**Comment by inexist3nce** [comment]
![0085 - cded09h](https://cloud.githubusercontent.com/assets/10874672/18987805/d9c93b2e-86d9-11e6-90fc-75539f41a27a.jpg)
